# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.update_verify_config:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    name: update-verify-config
    run-on-projects: []  # to make sure this never runs as part of CI
    shipping-phase: promote
    worker-type: b-linux
    worker:
        docker-image:
            in-tree: "update-verify"
        max-run-time: 3600
        artifacts:
            - name: public/build/update-verify.cfg
              path: /builds/worker/checkouts/gecko/update-verify.cfg
              type: file
    run:
        sparse-profile: mozharness
    extra:
        app-name: mail
        branch-prefix: comm
        archive-prefix:
            by-release-level:
                staging: "http://ftp.stage.mozaws.net/pub"
                production: "https://archive.mozilla.org/pub"
        previous-archive-prefix:
            by-release-level:
                staging: "https://archive.mozilla.org/pub"
                production: null
        aus-server:
            by-release-level:
                staging: "https://stage.balrog.nonprod.cloudops.mozgcp.net"
                production: "https://aus5.mozilla.org"
        include-version:
            by-release-type:
                beta: beta
                release: nonbeta
                default: beta
        last-watershed:
            by-release-type:
                beta: "76.0b1"
                release: "78.0"
                default: "default"

jobs:
    thunderbird-linux:
        shipping-product: thunderbird
        treeherder:
            symbol: UVC
            platform: linux32-shippable/opt
            kind: test
            tier: 1
        attributes:
            build_platform: linux-shippable
        extra:
            product: thunderbird
            platform: linux-i686
            updater-platform: linux-x86_64
            channel:
                by-release-type:
                    beta: "beta-localtest"
                    release: "release-localtest"
                    default: "default"
            mar-channel-id-override:
                by-release-type:
                    beta: beta
                    default: null

    thunderbird-linux64:
        shipping-product: thunderbird
        treeherder:
            symbol: UVC
            platform: linux64-shippable/opt
            kind: test
            tier: 1
        attributes:
            build_platform: linux64-shippable
        extra:
            product: thunderbird
            platform: linux-x86_64
            updater-platform: linux-x86_64
            channel:
                by-release-type:
                    beta: "beta-localtest"
                    release: "release-localtest"
                    default: "default"
            mar-channel-id-override:
                by-release-type:
                    beta: beta
                    default: null

    thunderbird-macosx64:
        shipping-product: thunderbird
        treeherder:
            symbol: UVC
            platform: osx-shippable/opt
            kind: test
            tier: 1
        attributes:
            build_platform: macosx64-shippable
        extra:
            product: thunderbird
            platform: mac
            updater-platform: linux-x86_64
            channel:
                by-release-type:
                    beta: "beta-localtest"
                    release: "release-localtest"
                    default: "default"
            mar-channel-id-override:
                by-release-type:
                    beta: beta
                    default: null

    thunderbird-win32:
        shipping-product: thunderbird
        treeherder:
            symbol: UVC
            platform: windows2012-32-shippable/opt
            kind: test
            tier: 1
        attributes:
            build_platform: win32-shippable
        extra:
            product: thunderbird
            platform: win32
            updater-platform: linux-x86_64
            channel:
                by-release-type:
                    beta: "beta-localtest"
                    release: "release-localtest"
                    default: "default"
            mar-channel-id-override:
                by-release-type:
                    beta: beta
                    default: null

    thunderbird-win64:
        shipping-product: thunderbird
        treeherder:
            symbol: UVC
            platform: windows2012-64-shippable/opt
            kind: test
            tier: 1
        attributes:
            build_platform: win64-shippable
        extra:
            product: thunderbird
            platform: win64
            updater-platform: linux-x86_64
            channel:
                by-release-type:
                    beta: "beta-localtest"
                    release: "release-localtest"
                    default: "default"
            mar-channel-id-override:
                by-release-type:
                    beta: beta
                    default: null
